//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Websitedata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Websitedata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Websitedata", typeof(Websitedata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आगाशिवनगर, ता. कराड जि. सातारा .
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@adarshshishuagashivnagar.edu.in.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +91 7057799082.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ७०५७७९९०८२.
        /// </summary>
        public static string phone1marathi {
            get {
                return ResourceManager.GetString("phone1marathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +91   .
        /// </summary>
        public static string phone2 {
            get {
                return ResourceManager.GetString("phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string phone2marathi {
            get {
                return ResourceManager.GetString("phone2marathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आदर्श शिशु विहार, आगाशिवनगर.
        /// </summary>
        public static string SchoolTitle {
            get {
                return ResourceManager.GetString("SchoolTitle", resourceCulture);
            }
        }
    }
}
